version: 2
jobs:
    build:
      docker:
        - image: nullworks/cathook-docker-ci:latest
      steps:
        - checkout
        - run: 
            name: "Compiling cathook"
            command: git submodule update --init --recursive; mkdir build; cd build; cmake -DEnableWarnings=0 ..; make -j8; cd ..
